CONFIG_ZMK_DISPLAY=y

CONFIG_DONGLE_SCREEN_EYES_ACTIVE=y
CONFIG_DONGLE_SCREEN_BACKGROUND_ACTIVE=y
CONFIG_DONGLE_SCREEN_LAYER_ACTIVE=n
CONFIG_DONGLE_SCREEN_MODIFIER_ACTIVE=n
CONFIG_DONGLE_SCREEN_WPM_ACTIVE=n
CONFIG_DONGLE_SCREEN_HORIZONTAL=y
CONFIG_DONGLE_SCREEN_FLIPPED=n
CONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=80
